/* Expansion symbols.

   The SVGs in img/game_icons/ are named after the printed expansion symbol,
   which is not what ArkhamDB calls the pack or the encounter set, so the two
   sides are matched here. The mapping itself is kept as a table in
   img/game_icons/game_icons_map.csv, and this file is generated from it: to
   change an assignment, edit that CSV and regenerate.

   PACKS is keyed by ArkhamDB pack `code` and holds the symbol of the box the
   pack came in — one symbol covers the deluxe box and its investigator and
   campaign reprints. SETS is keyed by `encounter_code`: every encounter set
   has its own symbol, so an encounter card gets that one instead. */
(function (global) {
  'use strict';

  var DIR = 'img/game_icons/';

  /* pack code -> file under img/game_icons/ */
  var PACKS = {
    'and':         "Chapter 02/202 - Investigator Decks/Andr\u00e9-Patel.svg",
    'aof':         "Chapter 01/00 - Core/Parallel-Investigator.svg",
    'aon':         "Chapter 01/Investigators/Parallel Investigators/All-or-Nothing.svg",
    'apot':        "Chapter 01/03 - The Path to Carcosa/PTC-A-Phantom-of-Truth.svg",
    'bad':         "Chapter 01/Investigators/Parallel Investigators/Bad-Blood.svg",
    'bbt':         "Chapter 01/05 - The Circle Undone/TCU-Before-the-Black-Throne.svg",
    'blbe':        "Chapter 01/Scenarios/11 - The Blob that ate everything else!/TBTAEE-Expansion.svg",
    'blob':        "Chapter 01/Scenarios/06 - The Blob that Ate Everything/TBTAE-Expansion.svg",
    'bob':         "Chapter 01/00 - Core/Novella.svg",
    'books':       "Chapter 01/00 - Core/Novella.svg",
    'bota':        "Chapter 01/02 - The Dunwich Legacy/DWL-Blood-on-the-Altar.svg",
    'bsr':         "Chapter 01/03 - The Path to Carcosa/PTC-Black-Stars-Rise.svg",
    'btb':         "Chapter 01/Investigators/Parallel Investigators/By-the-Book.svg",
    'car':         "Chapter 02/202 - Investigator Decks/Carolyn-Fern.svg",
    'coh':         "Chapter 01/Scenarios/02 - Carnevale of Horrors/COH-Expansion.svg",
    'core':        "Chapter 01/00 - Core/Core-Set.svg",
    'core_2026':   "Chapter 02/200 - Core 2026/Core 2026.svg",
    'cotr':        "Chapter 01/Scenarios/01 - Curse of the Rougarou/COTR-Expansion.svg",
    'dca':         "Chapter 01/03 - The Path to Carcosa/PTC-Dim-Carcosa.svg",
    'def':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Devil-Reef.svg",
    'dre':         "Chapter 01/00 - Core/Novella.svg",
    'dsm':         "Chapter 01/06 - The Dream-Eaters/TDE-Dark-Side-of-the-Moon.svg",
    'dwl':         "Chapter 01/02 - The Dunwich Legacy/DWL-Expansion.svg",
    'dwlc':        "Chapter 01/02 - The Dunwich Legacy/DWL-Expansion.svg",
    'dwlp':        "Chapter 01/02 - The Dunwich Legacy/DWL-Expansion.svg",
    'enc':         "Chapter 01/Investigators/Parallel Investigators/Enthralling-Encore.svg",
    'eoec':        "Chapter 01/08 - Edge of the Earth/EOEC-Campaign.svg",
    'eoep':        "Chapter 01/08 - Edge of the Earth/EOEP-Investigators.svg",
    'eotp':        "Chapter 01/03 - The Path to Carcosa/PTC-Echoes-of-the-Past.svg",
    'fgg':         "Chapter 01/05 - The Circle Undone/TCU-For-the-Greater-Good.svg",
    'fhvc':        "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Expansion.svg",
    'fhvp':        "Chapter 01/10 - The Feast of Hemlock Vale/FHVP-Investigators.svg",
    'film_fatale': "Chapter 01/Scenarios/13 - Film Fatale/FF-Expansion.svg",
    'fof':         "Chapter 01/Scenarios/09 - Fortune and Folly/FAF-Expansion.svg",
    'guardians':   "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-Expansion.svg",
    'har':         "Chapter 01/Investigators/Investigators Starter Decks/Harvey-Walters.svg",
    'hfa':         "Chapter 01/00 - Core/Parallel-Investigator.svg",
    'hhg':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Horror-in-High-Gear.svg",
    'hote':        "Chapter 01/04 - The Forgotten Age/TFA-Heart-of-the-Elders.svg",
    'hotel':       "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Expansion.svg",
    'hoth':        "Chapter 01/00 - Core/Novella.svg",
    'icc':         "Chapter 01/05 - The Circle Undone/TCU-In-the-Clutches-of-Chaos.svg",
    'iotv':        "Chapter 01/00 - Core/Novella.svg",
    'itd':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-In-Too-Deep.svg",
    'itm':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Into-the-Maelstrom.svg",
    'jac':         "Chapter 01/Investigators/Investigators Starter Decks/Jacqueline-Fine.svg",
    'lif':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-A-Light-in-the-Fog.svg",
    'litas':       "Chapter 01/02 - The Dunwich Legacy/DWL-Lost-in-Time-and-Space.svg",
    'lod':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-The-Lair-of-Dagon.svg",
    'lol':         "Chapter 01/Scenarios/03 - The Labyrinths of Lunacy/TLOL-Expansion.svg",
    'ltr':         "Chapter 01/Investigators/Parallel Investigators/Laid-to-Rest.svg",
    'mar':         "Chapter 02/202 - Investigator Decks/Marie-Lambeau.svg",
    'mig':         "Chapter 02/202 - Investigator Decks/Miguel-de-la-Cruz.svg",
    'mtt':         "Chapter 01/Scenarios/09 - Machinations Through Time/MTT-Expansion.svg",
    'nat':         "Chapter 01/Investigators/Investigators Starter Decks/Nathaniel-Cho.svg",
    'otr':         "Chapter 01/00 - Core/Parallel-Investigator.svg",
    'pap':         "Chapter 01/00 - Core/Parallel-Investigator.svg",
    'pnr':         "Chapter 01/06 - The Dream-Eaters/TDE-Point-of-No-Return.svg",
    'promo':       "Chapter 01/Investigators/Parallel Investigators/Promo.svg",
    'ptc':         "Chapter 01/03 - The Path to Carcosa/PTC-Expansion.svg",
    'ptcc':        "Chapter 01/03 - The Path to Carcosa/PTC-Expansion.svg",
    'ptcp':        "Chapter 01/03 - The Path to Carcosa/PTC-Expansion.svg",
    'ptr':         "Chapter 01/00 - Core/Parallel-Investigator.svg",
    'rcore':       "Chapter 01/00 - Core/Core-Set.svg",
    'rod':         "Chapter 01/Investigators/Parallel Investigators/Read-or-Die.svg",
    'rop':         "Chapter 01/Investigators/Parallel Investigators/Relics-from-the-Past.svg",
    'rtdwl':       "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Expansion.svg",
    'rtnotz':      "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Expansion.svg",
    'rtptc':       "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Expansion.svg",
    'rtr':         "Chapter 01/Investigators/Parallel Investigators/Red-Tide-Rising.svg",
    'rttcu':       "Chapter 01/05r - Return to The Circle Undone/RTTCU-Expansion.svg",
    'rttfa':       "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Expansion.svg",
    'sfk':         "Chapter 01/06 - The Dream-Eaters/TDE-The-Search-for-Kadath.svg",
    'sha':         "Chapter 01/04 - The Forgotten Age/TFA-Shattered-Aeons.svg",
    'ste':         "Chapter 01/Investigators/Investigators Starter Decks/Stella-Clark.svg",
    'tbb':         "Chapter 01/04 - The Forgotten Age/TFA-The-Boundary-Beyond.svg",
    'tcoa':        "Chapter 01/04 - The Forgotten Age/TFA-The-City-of-Archives.svg",
    'tcu':         "Chapter 01/05 - The Circle Undone/TCU-Expansion.svg",
    'tcuc':        "Chapter 01/05 - The Circle Undone/TCU-Expansion.svg",
    'tcup':        "Chapter 01/05 - The Circle Undone/TCU-Expansion.svg",
    'tdcc':        "Chapter 01/11 - The Drowned City/TDCC-Expansion.svg",
    'tdcp':        "Chapter 01/11 - The Drowned City/TDCP-Investigators.svg",
    'tde':         "Chapter 01/06 - The Dream-Eaters/TDE-Campaign.svg",
    'tdec':        "Chapter 01/06 - The Dream-Eaters/TDE-Campaign.svg",
    'tdep':        "Chapter 01/06 - The Dream-Eaters/TDE-Campaign.svg",
    'tdg':         "Chapter 01/00 - Core/Novella.svg",
    'tdor':        "Chapter 01/00 - Core/Novella.svg",
    'tdoy':        "Chapter 01/04 - The Forgotten Age/TFA-The-Depths-of-Yoth.svg",
    'tece':        "Chapter 01/02 - The Dunwich Legacy/DWL-The-Essex-County-Express.svg",
    'tfa':         "Chapter 01/04 - The Forgotten Age/TFA-Expansion.svg",
    'tfac':        "Chapter 01/04 - The Forgotten Age/TFA-Expansion.svg",
    'tfap':        "Chapter 01/04 - The Forgotten Age/TFA-Expansion.svg",
    'tftbw':       "Chapter 01/00 - Core/Novella.svg",
    'tic':         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Campaign.svg",
    'ticc':        "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Campaign.svg",
    'ticp':        "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Campaign.svg",
    'tmg':         "Chapter 01/Scenarios/12 - The Midwinter Gala/TMWG-Expansion.svg",
    'tmm':         "Chapter 01/02 - The Dunwich Legacy/DWL-The-Miskatonic-Museum.svg",
    'tof':         "Chapter 01/04 - The Forgotten Age/TFA-Threads-of-Fate.svg",
    'tom':         "Chapter 02/202 - Investigator Decks/Tommy-Muldoon.svg",
    'tpm':         "Chapter 01/03 - The Path to Carcosa/PTC-The-Pallid-Mask.svg",
    'tsh':         "Chapter 01/06 - The Dream-Eaters/TDE-A-Thousand-Shapes-of-Horror.svg",
    'tskc':        "Chapter 01/09 - The Skarlet Keys/TSKC-Expansion.svg",
    'tskp':        "Chapter 01/09 - The Skarlet Keys/TSKP-Investigators.svg",
    'tsn':         "Chapter 01/05 - The Circle Undone/TCU-The-Secret-Name.svg",
    'tuo':         "Chapter 01/03 - The Path to Carcosa/PTC-The-Unspeakable-Oath.svg",
    'uad':         "Chapter 01/05 - The Circle Undone/TCU-Union-and-Disillusion.svg",
    'uau':         "Chapter 01/02 - The Dunwich Legacy/DWL-Undimensioned-and-Unseen.svg",
    'wda':         "Chapter 01/02 - The Dunwich Legacy/DWL-Where-Doom-Awaits.svg",
    'wgd':         "Chapter 01/06 - The Dream-Eaters/TDE-Where-the-Gods-Dwell.svg",
    'win':         "Chapter 01/Investigators/Investigators Starter Decks/Winifred-Habbamock.svg",
    'woc':         "Chapter 01/06 - The Dream-Eaters/TDE-Weaver-of-the-Cosmos.svg",
    'wog':         "Chapter 01/Scenarios/07 - War of the Outer Worlds/WOTOG-Expansion.svg",
    'wos':         "Chapter 01/05 - The Circle Undone/TCU-The-Wages-of-Sin.svg"
  };

  /* encounter set code -> file under img/game_icons/ */
  var SETS = {
    'a_light_in_the_fog':                             "Chapter 01/07 - The Innsmouth Conspiracy/TIC-A-Light-in-the-Fog.svg",
    'a_phantom_of_truth':                             "Chapter 01/03 - The Path to Carcosa/PTC-A-Phantom-of-Truth.svg",
    'a_thousand_shapes_of_horror':                    "Chapter 01/06 - The Dream-Eaters/TDE-A-Thousand-Shapes-of-Horror.svg",
    'abominable_contessa':                            "Chapter 01/Scenarios/13 - Film Fatale/FF-Abominable-Contessa.svg",
    'abyssal_gifts':                                  "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-Abyssal-Gifts.svg",
    'abyssal_tribute':                                "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-Abyssal-Tribute.svg",
    'agents_of_atlach_nacha':                         "Chapter 01/06 - The Dream-Eaters/TDE-Agents-of-Atlach-Nacha.svg",
    'agents_of_azathoth':                             "Chapter 01/05 - The Circle Undone/TCU-Agents-of-Azathoth.svg",
    'agents_of_cthulhu':                              "Chapter 01/01 - Night of the Zealot/NOTZ-Agents-of-Cthulhu.svg",
    'agents_of_dagon':                                "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Agents-of-Dagon.svg",
    'agents_of_hastur':                               "Chapter 01/01 - Night of the Zealot/NOTZ-Agents-of-Hastur.svg",
    'agents_of_hydra':                                "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Agents-of-Hydra.svg",
    'agents_of_nyarlathotep':                         "Chapter 01/06 - The Dream-Eaters/TDE-Agents-of-Nyarlathotep.svg",
    'agents_of_shub':                                 "Chapter 01/01 - Night of the Zealot/NOTZ-Agents-of-Shub-Niggurath.svg",
    'agents_of_the_colour':                           "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Agents-of-the-Colour.svg",
    'agents_of_the_outside':                          "Chapter 01/09 - The Skarlet Keys/TSKC-Agents-of-the-Outside.svg",
    'agents_of_the_unknown':                          "Chapter 01/08 - Edge of the Earth/EOEC-Agents-of-the-Unknown.svg",
    'agents_of_yig':                                  "Chapter 01/04 - The Forgotten Age/TFA-Agents-of-Yig.svg",
    'agents_of_yog':                                  "Chapter 01/01 - Night of the Zealot/NOTZ-Agents-of-Yog-Sothoth.svg",
    'agents_of_yuggoth':                              "Chapter 01/09 - The Skarlet Keys/TSKC-Agents-of-Yuggoth.svg",
    'alien_interference':                             "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Alien-Interference.svg",
    'alien_machinery':                                "Chapter 01/11 - The Drowned City/TDCC-Alien-Machinery.svg",
    'all_or_nothing':                                 "Chapter 01/Investigators/Parallel Investigators/All-or-Nothing.svg",
    'ancient_evils':                                  "Chapter 01/01 - Night of the Zealot/NOTZ-Ancient-Evils.svg",
    'anettes_coven':                                  "Chapter 01/05 - The Circle Undone/TCU-Anette\u2019s-Coven.svg",
    'arcane_lock':                                    "Chapter 02/201 - Brethren of Ash/BOA-Arcane-Lock.svg",
    'arkham':                                         "Chapter 01/01 - Night of the Zealot/NOTZ-The-Midnight-Masks.svg",
    'arkham_ch2':                                     "Chapter 02/201 - Brethren of Ash/BOA-Arkham.svg",
    'arkham_sewers':                                  "Chapter 02/201 - Brethren of Ash/BOA-Sewers.svg",
    'armitages_fate':                                 "Chapter 01/02 - The Dunwich Legacy/DWL-Armitage\u2019s-Fate.svg",
    'ashen_pilgrims':                                 "Chapter 02/201 - Brethren of Ash/BOA-Ashen-Pilgrims.svg",
    'at_deaths_doorstep':                             "Chapter 01/05 - The Circle Undone/TCU-At-Death\u2019s-Doorstep.svg",
    'bad_blood':                                      "Chapter 01/Investigators/Parallel Investigators/Bad-Blood.svg",
    'bad_luck':                                       "Chapter 01/02 - The Dunwich Legacy/DWL-Bad-Luck.svg",
    'bad_weather':                                    "Chapter 02/201 - Brethren of Ash/BOA-Bad-Weather.svg",
    'bayou':                                          "Chapter 01/Scenarios/01 - Curse of the Rougarou/COTR-The-Bayou.svg",
    'beast_thralls':                                  "Chapter 01/02 - The Dunwich Legacy/DWL-Beast-thralls.svg",
    'before_the_black_throne':                        "Chapter 01/05 - The Circle Undone/TCU-Before-the-Black-Throne.svg",
    'beyond_the_beyond':                              "Chapter 01/09 - The Skarlet Keys/TSKC-Beyond-the-Beyond.svg",
    'beyond_the_gates_of_sleep':                      "Chapter 01/06 - The Dream-Eaters/TDE-Beyond-the-Gates-of-Sleep.svg",
    'beyond_the_threshold':                           "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Beyond-the-Threshold.svg",
    'bishops_thralls':                                "Chapter 01/02 - The Dunwich Legacy/DWL-Bishop\u2019s-Thralls.svg",
    'black_stars_rise':                               "Chapter 01/03 - The Path to Carcosa/PTC-Black-Stars-Rise.svg",
    'blight':                                         "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Blight.svg",
    'blob':                                           "Chapter 01/Scenarios/06 - The Blob that Ate Everything/TBTAE-The-Blob-That-Ate-Everything.svg",
    'blob_epic_multiplayer':                          "Chapter 01/00 - Core/Epic-Multiplayer.svg",
    'blob_single_group':                              "Chapter 01/00 - Core/Single-Group.svg",
    'blob_that_ate_everything_else':                  "Chapter 01/Scenarios/11 - The Blob that ate everything else!/TBTAEE-he-Blob-That-Ate-Everything-Else.svg",
    'blood_on_the_altar':                             "Chapter 01/02 - The Dunwich Legacy/DWL-Blood-on-the-Altar.svg",
    'bloodthirsty_spirits':                           "Chapter 01/05r - Return to The Circle Undone/RTTCU-Bloodthirsty-Spirits.svg",
    'brotherhood_of_the_beast':                       "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-Brotherhood-of-the-Beast.svg",
    'by_the_book':                                    "Chapter 01/Investigators/Parallel Investigators/By-the-Book.svg",
    'byakhee':                                        "Chapter 01/03 - The Path to Carcosa/PTC-Byakhee.svg",
    'bystanders':                                     "Chapter 02/201 - Brethren of Ash/BOA-Bystanders.svg",
    'children_of_paradise':                           "Chapter 01/Scenarios/07 - War of the Outer Worlds/WOTOG-Children-of-Paradise.svg",
    'chilling_cold':                                  "Chapter 01/01 - Night of the Zealot/NOTZ-Chilling-Cold.svg",
    'chilling_mists':                                 "Chapter 01/05r - Return to The Circle Undone/RTTCU-Chilling-Mists.svg",
    'city_of_sins':                                   "Chapter 01/05 - The Circle Undone/TCU-City-of-Sins.svg",
    'city_of_the_damned':                             "Chapter 01/05r - Return to The Circle Undone/RTTCU-City-of-the-Damned.svg",
    'city_of_the_elder_things':                       "Chapter 01/08 - Edge of the Earth/EOEC-City-of-the-Elder-Things.svg",
    'cleanup_crew':                                   "Chapter 01/09 - The Skarlet Keys/TSKC-Cleanup-Crew.svg",
    'congress_of_the_keys':                           "Chapter 01/09 - The Skarlet Keys/TSKC-Congress-of-the-Keys.svg",
    'corsairs':                                       "Chapter 01/06 - The Dream-Eaters/TDE-Corsairs.svg",
    'cosmic_evils':                                   "Chapter 02/201 - Brethren of Ash/BOA-Cosmic-Evils.svg",
    'cosmic_journey':                                 "Chapter 01/Scenarios/13 - Film Fatale/FF-Cosmic-Journey.svg",
    'cosmic_legacy':                                  "Chapter 01/11 - The Drowned City/TDCC-Cosmic-Legacy.svg",
    'court_of_the_ancients':                          "Chapter 01/11 - The Drowned City/TDCC-Court-of-the-Ancients.svg",
    'creatures_in_the_ice':                           "Chapter 01/08 - Edge of the Earth/EOEC-Creatures-in-the-Ice.svg",
    'creatures_of_the_deep':                          "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Creatures-of-the-Deep.svg",
    'creatures_of_the_underworld':                    "Chapter 01/06 - The Dream-Eaters/TDE-Creatures-of-the-Underworld.svg",
    'creeping_cold':                                  "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Creeping-Cold.svg",
    'crimson_conspiracy':                             "Chapter 01/09 - The Skarlet Keys/TSKC-Crimson-Conspiracy.svg",
    'cult_of_pnakotus':                               "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Cult-of-Pnakotus.svg",
    'cult_of_the_yellow_sign':                        "Chapter 01/03 - The Path to Carcosa/PTC-Cult-of-the-Yellow-Sign.svg",
    'cultists':                                       "Chapter 01/01 - Night of the Zealot/NOTZ-Cult-of-Um\u00f4rdhoth.svg",
    'cultists_ch2':                                   "Chapter 02/201 - Brethren of Ash/BOA-Cultists.svg",
    'curtain_call':                                   "Chapter 01/03 - The Path to Carcosa/PTC-Curtain-Call.svg",
    'dancing_mad':                                    "Chapter 01/09 - The Skarlet Keys/TSKC-Dancing-Mad.svg",
    'dark_rituals':                                   "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Dark-Rituals.svg",
    'dark_side_of_the_moon':                          "Chapter 01/06 - The Dream-Eaters/TDE-Dark-Side-of-the-Moon.svg",
    'dark_veiling':                                   "Chapter 01/09 - The Skarlet Keys/TSKC-Dark-Veiling.svg",
    'day_of_rain':                                    "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Day-of-Rain.svg",
    'day_of_rest':                                    "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Day-of-Rest.svg",
    'day_of_the_feast':                               "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Day-of-the-Feast.svg",
    'dead_ends':                                      "Chapter 02/201 - Brethren of Ash/BOA-Dead-Ends.svg",
    'dead_heat':                                      "Chapter 01/09 - The Skarlet Keys/TSKC-Dead-Heat.svg",
    'deadly_weather':                                 "Chapter 01/08 - Edge of the Earth/EOEC-Deadly-Weather.svg",
    'dealings_in_the_dark':                           "Chapter 01/09 - The Skarlet Keys/TSKC-Dealings-in-the-Dark.svg",
    'death_of_stars':                                 "Chapter 01/Scenarios/07 - War of the Outer Worlds/WOTOG-Death-of-Stars.svg",
    'decay':                                          "Chapter 01/03 - The Path to Carcosa/PTC-Decay-&-Filth.svg",
    'decaying_reality':                               "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Decaying-Reality.svg",
    'deep_ones':                                      "Chapter 01/11 - The Drowned City/TDCC-Deep-Ones.svg",
    'delusions':                                      "Chapter 01/03 - The Path to Carcosa/PTC-Delusions.svg",
    'delusory_evils':                                 "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Delusory-Evils.svg",
    'descent_into_the_pitch':                         "Chapter 01/06 - The Dream-Eaters/TDE-Descent-into-the-Pitch.svg",
    'devil_reef':                                     "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Devil-Reef.svg",
    'dim_carcosa':                                    "Chapter 01/03 - The Path to Carcosa/PTC-Dim-Carcosa.svg",
    'disappearance_at_the_twilight_estate':           "Chapter 01/05 - The Circle Undone/TCU-Disappearance-at-the-Twilight-Estate.svg",
    'dogs_of_war':                                    "Chapter 01/09 - The Skarlet Keys/TSKC-Dogs-of-War.svg",
    'domination':                                     "Chapter 01/11 - The Drowned City/TDCC-Domination.svg",
    'doomed_expedition':                              "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Doomed-Expedition.svg",
    'dreamers_curse':                                 "Chapter 01/06 - The Dream-Eaters/TDE-Dreamer\u2019s-Curse.svg",
    'dreamlands':                                     "Chapter 01/06 - The Dream-Eaters/TDE-Dreamlands.svg",
    'dreams':                                         "Chapter 01/11 - The Drowned City/TDCC-Dreams.svg",
    'dunwich':                                        "Chapter 01/02 - The Dunwich Legacy/DWL-Dunwich.svg",
    'echoes_of_the_past':                             "Chapter 01/03 - The Path to Carcosa/PTC-Echoes-of-the-Past.svg",
    'elder_mist':                                     "Chapter 01/11 - The Drowned City/TDCC-Elder-Mist.svg",
    'elder_things':                                   "Chapter 01/08 - Edge of the Earth/EOEC-Elder-Things.svg",
    'eldritch_lore':                                  "Chapter 02/201 - Brethren of Ash/BOA-Eldritch-Lore.svg",
    'enthralling_encore':                             "Chapter 01/Investigators/Parallel Investigators/Enthralling-Encore.svg",
    'epic_multiplayer':                               "Chapter 01/00 - Core/Epic-Multiplayer.svg",
    'erratic_fear':                                   "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Erratic-Fear.svg",
    'essex_county_express':                           "Chapter 01/02 - The Dunwich Legacy/DWL-The-Essex-County-Express.svg",
    'evil_portents':                                  "Chapter 01/03 - The Path to Carcosa/PTC-Evil-Portents.svg",
    'excelsior_management':                           "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Excelsior-Management.svg",
    'expedition':                                     "Chapter 01/04 - The Forgotten Age/TFA-Expedition.svg",
    'expedition_team':                                "Chapter 01/08 - Edge of the Earth/EOEC-Expedition-Team.svg",
    'extracurricular_activity':                       "Chapter 01/02 - The Dunwich Legacy/DWL-Extracurricular-Activity.svg",
    'eztli':                                          "Chapter 01/04 - The Forgotten Age/TFA-The-Doom-of-Eztli.svg",
    'fatal_mirage':                                   "Chapter 01/08 - Edge of the Earth/EOEC-Fatal-Mirage.svg",
    'fate_of_the_vale':                               "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Fate-of-the-Vale.svg",
    'film_fatale':                                    "Chapter 01/Scenarios/13 - Film Fatale/FF-Film-Fatale.svg",
    'fire':                                           "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Fire!.svg",
    'fire_ch2':                                       "Chapter 02/201 - Brethren of Ash/BOA-Fire!.svg",
    'flood':                                          "Chapter 01/03 - The Path to Carcosa/PTC-The-Flood-Below.svg",
    'flooded_caverns':                                "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Flooded-Caverns.svg",
    'flux':                                           "Chapter 01/04 - The Forgotten Age/TFA-Temporal-Flux.svg",
    'flying_terrors':                                 "Chapter 02/201 - Brethren of Ash/BOA-Flying-Terrors.svg",
    'fog_over_innsmouth':                             "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Fog-over-Innsmouth.svg",
    'for_the_greater_good':                           "Chapter 01/05 - The Circle Undone/TCU-For-the-Greater-Good.svg",
    'forgotten_island':                               "Chapter 01/Scenarios/13 - Film Fatale/FF-Forgotten-Island.svg",
    'fortune_and_folly':                              "Chapter 01/Scenarios/09 - Fortune and Folly/FAF-Fortune-and-Folly.svg",
    'fortunes_chosen':                                "Chapter 01/Scenarios/09 - Fortune and Folly/FAF-Fortune\u2019s-Chosen.svg",
    'gangs_of_arkham':                                "Chapter 02/201 - Brethren of Ash/BOA-Gangs-of-Arkham.svg",
    'ghouls':                                         "Chapter 01/01 - Night of the Zealot/NOTZ-Ghouls.svg",
    'ghouls_of_umôrdhoth':                            "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Ghouls-of-Um\u00f4rdhoth.svg",
    'globetrotting':                                  "Chapter 01/09 - The Skarlet Keys/TSKC-Globetrotting.svg",
    'guardians_of_time':                              "Chapter 01/04 - The Forgotten Age/TFA-Guardians-of-Time.svg",
    'hallucinations':                                 "Chapter 02/201 - Brethren of Ash/BOA-Hallucinations.svg",
    'hasturs_envoys':                                 "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Hastur\u2019s-Envoys.svg",
    'hasturs_gift':                                   "Chapter 01/03 - The Path to Carcosa/PTC-Hastur\u2019s-Gift.svg",
    'hauntings':                                      "Chapter 01/03 - The Path to Carcosa/PTC-Hauntings.svg",
    'hazards_of_antarctica':                          "Chapter 01/08 - Edge of the Earth/EOEC-Hazards-of-Antarctica.svg",
    'heart_of_the_elders':                            "Chapter 01/04 - The Forgotten Age/TFA-Heart-of-the-Elders.svg",
    'heirlooms':                                      "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Heirlooms.svg",
    'hemlock_house':                                  "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Hemlock-House.svg",
    'hexcraft':                                       "Chapter 01/05r - Return to The Circle Undone/RTTCU-Hexcraf.svg",
    'hideous_abominations':                           "Chapter 01/02 - The Dunwich Legacy/DWL-Hideous-Abominations.svg",
    'horror_in_high_gear':                            "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Horror-in-High-Gear.svg",
    'horrors_in_the_rock':                            "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Horrors-in-the-Rock.svg",
    'ice_and_death':                                  "Chapter 01/08 - Edge of the Earth/EOEC-Ice-and-Death.svg",
    'impending_evils':                                "Chapter 01/05r - Return to The Circle Undone/RTTCU-Impending-Evils.svg",
    'in_the_clutches_of_chaos':                       "Chapter 01/05 - The Circle Undone/TCU-In-the-Clutches-of-Chaos.svg",
    'in_the_labyrinths_of_lunacy':                    "Chapter 01/Scenarios/03 - The Labyrinths of Lunacy/TLOL-The-Labyrinths-of-Lunacy.svg",
    'in_too_deep':                                    "Chapter 01/07 - The Innsmouth Conspiracy/TIC-In-Too-Deep.svg",
    'inexorable_fate':                                "Chapter 01/05 - The Circle Undone/TCU-Inexorable-Fate.svg",
    'inhabitants_of_carcosa':                         "Chapter 01/03 - The Path to Carcosa/PTC-Inhabitants-of-Carcosa.svg",
    'into_the_maelstrom':                             "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Into-the-Maelstrom.svg",
    'knyan':                                          "Chapter 01/04 - The Forgotten Age/TFA-K\u2019n-yan.svg",
    'laid_to_rest':                                   "Chapter 01/Investigators/Parallel Investigators/Laid-to-Rest.svg",
    'left_behind':                                    "Chapter 01/08 - Edge of the Earth/EOEC-Left-Behind.svg",
    'locked_doors':                                   "Chapter 01/01 - Night of the Zealot/NOTZ-Locked-Doors.svg",
    'lost_in_the_night':                              "Chapter 01/08 - Edge of the Earth/EOEC-Lost-in-the-Night.svg",
    'lost_in_time_and_space':                         "Chapter 01/02 - The Dunwich Legacy/DWL-Lost-in-Time-and-Space.svg",
    'machinations_through_time':                      "Chapter 01/Scenarios/09 - Machinations Through Time/MTT-Machinations-Through-Time.svg",
    'machinations_through_time_epic_multiplayer':     "Chapter 01/00 - Core/Epic-Multiplayer.svg",
    'machinations_through_time_single_group':         "Chapter 01/00 - Core/Single-Group.svg",
    'mad_science':                                    "Chapter 02/201 - Brethren of Ash/BOA-Mad-Science.svg",
    'maddening_delusions':                            "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Maddening-Delusions.svg",
    'malfunction':                                    "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Malfunction.svg",
    'memorials_of_the_lost':                          "Chapter 01/08 - Edge of the Earth/EOEC-Memorials-of-the-Lost.svg",
    'merging_realities':                              "Chapter 01/06 - The Dream-Eaters/TDE-Merging-Realities.svg",
    'miasma':                                         "Chapter 01/08 - Edge of the Earth/EOEC-Miasma.svg",
    'migo_incursion':                                 "Chapter 01/Scenarios/06 - The Blob that Ate Everything/TBTAE-Mi-Go-Incursion.svg",
    'migo_incursion_2':                               "Chapter 01/Scenarios/11 - The Blob that ate everything else!/TBTAEE-Mi-Go-Incursion-II.svg",
    'miskatonic_university':                          "Chapter 02/201 - Brethren of Ash/BOA-Miskatonic-University.svg",
    'murder_at_the_excelsior_hotel':                  "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Murder-at-the-Excelsior-Hotel.svg",
    'music_of_the_damned':                            "Chapter 01/05 - The Circle Undone/TCU-Music-of-the-Damned.svg",
    'mutations':                                      "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Mutations.svg",
    'myconids':                                       "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Myconids.svg",
    'mysteries_abound':                               "Chapter 01/09 - The Skarlet Keys/TSKC-Mysteries-Abound.svg",
    'nameless_horrors':                               "Chapter 01/08 - Edge of the Earth/EOEC-Nameless-Horrors.svg",
    'naomis_crew':                                    "Chapter 01/02 - The Dunwich Legacy/DWL-Naomi\u2019s-Crew.svg",
    'neurotic_fear':                                  "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Neurotic-Fear.svg",
    'nightgaunts':                                    "Chapter 01/01 - Night of the Zealot/NOTZ-Nightgaunts.svg",
    'obsidian_canyons':                               "Chapter 01/11 - The Drowned City/TDCC-Obsidian-Canyons.svg",
    'on_thin_ice':                                    "Chapter 01/09 - The Skarlet Keys/TSKC-On-Thin-Ice.svg",
    'one_last_job':                                   "Chapter 01/11 - The Drowned City/TDCC-One-Last-Job.svg",
    'outsiders':                                      "Chapter 01/09 - The Skarlet Keys/TSKC-Outsiders.svg",
    'penguins':                                       "Chapter 01/08 - Edge of the Earth/EOEC-Penguins.svg",
    'pentagram':                                      "Chapter 01/01 - Night of the Zealot/NOTZ-Dark-Cult.svg",
    'people_of_arkham':                               "Chapter 02/201 - Brethren of Ash/BOA-People-of-Arkham.svg",
    'pilgrims':                                       "Chapter 01/11 - The Drowned City/TDCC-Pilgrims.svg",
    'pillars_of_judgment':                            "Chapter 01/04 - The Forgotten Age/TFA-Pillars-of-Judgment.svg",
    'plan_in_shambles':                               "Chapter 01/Scenarios/09 - Fortune and Folly/FAF-Plan-in-Shambles.svg",
    'pnakotic_brotherhood':                           "Chapter 01/04 - The Forgotten Age/TFA-Pnakotic-Brotherhood.svg",
    'point_of_no_return':                             "Chapter 01/06 - The Dream-Eaters/TDE-Point-of-No-Return.svg",
    'poison':                                         "Chapter 01/04 - The Forgotten Age/TFA-Poison.svg",
    'queen_of_ash':                                   "Chapter 02/201 - Brethren of Ash/BOA-Queen-of-Ash.svg",
    'rainforest':                                     "Chapter 01/04 - The Forgotten Age/TFA-Rainforest.svg",
    'rats':                                           "Chapter 01/01 - Night of the Zealot/NOTZ-Rats.svg",
    'read_or_die':                                    "Chapter 01/Investigators/Parallel Investigators/Read-or-Die.svg",
    'realm_of_death':                                 "Chapter 01/05 - The Circle Undone/TCU-Realm-of-Death.svg",
    'red_coterie':                                    "Chapter 01/09 - The Skarlet Keys/TSKC-Red-Coterie.svg",
    'red_tide_rising':                                "Chapter 01/Investigators/Parallel Investigators/Red-Tide-Rising.svg",
    'reeking_decay':                                  "Chapter 02/201 - Brethren of Ash/BOA-Reeking-Decay.svg",
    'refractions':                                    "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Refractions.svg",
    'relics_of_the_past':                             "Chapter 01/Investigators/Parallel Investigators/Relics-from-the-Past.svg",
    'residents':                                      "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Residents.svg",
    'resurgent_evils':                                "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Resurgent-Evils.svg",
    'return_cult':                                    "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Cult-of-Um\u00f4rdhoth-(new).svg",
    'return_to_a_phantom_of_truth':                   "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-A-Phantom-of-Truth.svg",
    'return_to_at_deaths_doorstep':                   "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-At-Death\u2019s-Doorstep.svg",
    'return_to_before_the_black_throne':              "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-Before-the-Black-Throne.svg",
    'return_to_black_stars_rise':                     "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-Black-Stars-Rise.svg",
    'return_to_blood_on_the_altar':                   "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-Blood-on-the-Altar.svg",
    'return_to_curtain_call':                         "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-Curtain-Call.svg",
    'return_to_dim_carcosa':                          "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-Dim-Carcosa.svg",
    'return_to_disappearance_at_the_twilight_estate': "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-Disappearance-at-the-Twilight-Estate.svg",
    'return_to_echoes_of_the_past':                   "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-Echoes-of-the-Past.svg",
    'return_to_extracurricular_activities':           "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-Extracurricular-Activities.svg",
    'return_to_for_the_greater_good':                 "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-For-the-Greater-Good.svg",
    'return_to_in_the_clutches_of_chaos':             "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-In-the-Clutches-of-Chaos.svg",
    'return_to_knyan':                                "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-Heart-of-the-Elders.svg",
    'return_to_lost_in_time_and_space':               "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-Lost-in-Time-and-Space.svg",
    'return_to_pillars_of_judgment':                  "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-Heart-of-the-Elders.svg",
    'return_to_shattered_aeons':                      "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-Shattered-Aeons.svg",
    'return_to_the_boundary_beyond':                  "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-The-Boundary-Beyond.svg",
    'return_to_the_city_of_archives':                 "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-The-City-of-Archives.svg",
    'return_to_the_depths_of_yoth':                   "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-The-Depths-of-Yoth.svg",
    'return_to_the_devourer_below':                   "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Return-to-The-Devourer-Below.svg",
    'return_to_the_doom_of_eztli':                    "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-The-Doom-of-Eztli.svg",
    'return_to_the_essex_county_express':             "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-The-Essex-County-Express.svg",
    'return_to_the_gathering':                        "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Return-to-The-Gathering.svg",
    'return_to_the_house_always_wins':                "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-The-House-Always-Wins.svg",
    'return_to_the_last_king':                        "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-The-Last-King.svg",
    'return_to_the_midnight_masks':                   "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-Return-to-The-Midnight-Masks.svg",
    'return_to_the_miskatonic_museum':                "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-The-Miskatonic-Museum.svg",
    'return_to_the_pallid_mask':                      "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-The-Pallid-Mask.svg",
    'return_to_the_rainforest':                       "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-the-Rainforest.svg",
    'return_to_the_secret_name':                      "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-The-Secret-Name.svg",
    'return_to_the_unspeakable_oath':                 "Chapter 01/03r - Return to The Path to Carcosa/RTPTC-Return-to-The-Unspeakable-Oath.svg",
    'return_to_the_untamed_wilds':                    "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-The-Untamed-Wilds.svg",
    'return_to_the_wages_of_sin':                     "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-The-Wages-of-Sin.svg",
    'return_to_the_witching_hour':                    "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-The-Witching-Hour.svg",
    'return_to_threads_of_fate':                      "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-Threads-of-Fate.svg",
    'return_to_turn_back_time':                       "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Return-to-Turn-Back-Time.svg",
    'return_to_undimensioned_and_unseen':             "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-Undimensioned-and-Unseen.svg",
    'return_to_union_and_disillusion':                "Chapter 01/05r - Return to The Circle Undone/RTTCU-Return-to-Union-and-Disillusion.svg",
    'return_to_where_doom_awaits':                    "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Return-to-Where-Doom-Awaits.svg",
    'riddles_and_rain':                               "Chapter 01/09 - The Skarlet Keys/TSKC-Riddles-and-Rain.svg",
    'rising_tide':                                    "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Rising-Tide.svg",
    'rlyeh':                                          "Chapter 01/11 - The Drowned City/TDCC-R\u2019lyeh.svg",
    'rougarou':                                       "Chapter 01/Scenarios/01 - Curse of the Rougarou/COTR-Curse-of-the-Rougarou.svg",
    'ruins':                                          "Chapter 01/04 - The Forgotten Age/TFA-Forgotten-Ruins.svg",
    'sands_of_egypt':                                 "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-Sands-of-Egypt.svg",
    'sanguine_shadows':                               "Chapter 01/09 - The Skarlet Keys/TSKC-Sanguine-Shadows.svg",
    'scarlet_sorcery':                                "Chapter 01/09 - The Skarlet Keys/TSKC-Scarlet-Sorcery.svg",
    'secret_doors':                                   "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Secret-Doors.svg",
    'secret_war':                                     "Chapter 01/09 - The Skarlet Keys/TSKC-Secret-War.svg",
    'secrets_of_the_universe':                        "Chapter 01/05 - The Circle Undone/TCU-Secrets-of-the-Universe.svg",
    'seeping_nightmares':                             "Chapter 01/08 - Edge of the Earth/EOEC-Seeping-Nightmares.svg",
    'sepulchre_of_the_sleeper':                       "Chapter 01/11 - The Drowned City/TDCC-Sepulchre-of-the-Sleeper.svg",
    'serpents':                                       "Chapter 01/04 - The Forgotten Age/TFA-Serpents.svg",
    'shades_of_suffering':                            "Chapter 01/09 - The Skarlet Keys/TSKC-Shades-of-Suffering.svg",
    'shadow_of_a_doubt':                              "Chapter 01/09 - The Skarlet Keys/TSKC-Shadow-of-a-Doubt.svg",
    'shattered_aeons':                                "Chapter 01/04 - The Forgotten Age/TFA-Shattered-Aeons.svg",
    'shattered_memories':                             "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Shattered-Memories.svg",
    'shoggoths':                                      "Chapter 01/08 - Edge of the Earth/EOEC-Shoggoths.svg",
    'silence_and_mystery':                            "Chapter 01/08 - Edge of the Earth/EOEC-Silence-and-Mystery.svg",
    'silver_twilight_lodge':                          "Chapter 01/05 - The Circle Undone/TCU-Silver-Twilight-Lodge.svg",
    'single_group':                                   "Chapter 01/00 - Core/Single-Group.svg",
    'sins_of_the_past':                               "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Sins-of-the-Past.svg",
    'smoke_and_mirrors':                              "Chapter 02/201 - Brethren of Ash/BOA-Smoke-and-Mirrors.svg",
    'sorcery':                                        "Chapter 01/02 - The Dunwich Legacy/DWL-Sorcery.svg",
    'spatial_anomaly':                                "Chapter 01/09 - The Skarlet Keys/TSKC-Spatial-Anomaly.svg",
    'spectral_predators':                             "Chapter 01/05 - The Circle Undone/TCU-Spectral-Predators.svg",
    'spiders':                                        "Chapter 01/06 - The Dream-Eaters/TDE-Spiders.svg",
    'spreading_corruption':                           "Chapter 01/09 - The Skarlet Keys/TSKC-Spreading-Corruption.svg",
    'spreading_flames':                               "Chapter 02/201 - Brethren of Ash/BOA-Spreading-Flames.svg",
    'star_spawn':                                     "Chapter 01/11 - The Drowned City/TDCC-Star-Spawn.svg",
    'stirring_in_the_deep':                           "Chapter 01/08 - Edge of the Earth/EOEC-Stirring-in-the-Deep.svg",
    'stowaways':                                      "Chapter 01/11 - The Drowned City/TDCC-Stowaways.svg",
    'strange_happenings':                             "Chapter 01/09 - The Skarlet Keys/TSKC-Strange-Happenings.svg",
    'stranger':                                       "Chapter 01/03 - The Path to Carcosa/PTC-The-Stranger.svg",
    'striking_fear':                                  "Chapter 01/01 - Night of the Zealot/NOTZ-Striking-Fear.svg",
    'swarm_of_assimilation':                          "Chapter 01/Scenarios/07 - War of the Outer Worlds/WOTOG-Swarm-of-Assimilation.svg",
    'syzygy':                                         "Chapter 01/07 - The Innsmouth Conspiracy/TIC-Syzygy.svg",
    'tasks':                                          "Chapter 01/11 - The Drowned City/TDCC-Tasks.svg",
    'tdc_expedition':                                 "Chapter 01/11 - The Drowned City/TDCC-Expedition.svg",
    'tdc_flood':                                      "Chapter 01/11 - The Drowned City/TDCC-Flood.svg",
    'tekelili':                                       "Chapter 01/08 - Edge of the Earth/EOEC-Tekeli-li.svg",
    'temporal_hunters':                               "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Temporal-Hunters.svg",
    'tentacles':                                      "Chapter 01/01 - Night of the Zealot/NOTZ-The-Devourer-Below.svg",
    'terror_of_the_vale':                             "Chapter 01/06 - The Dream-Eaters/TDE-Terror-of-the-Vale.svg",
    'the_apiary':                                     "Chapter 01/11 - The Drowned City/TDCC-The-Apiary.svg",
    'the_beyond':                                     "Chapter 01/02 - The Dunwich Legacy/DWL-The-Beyond.svg",
    'the_boundary_beyond':                            "Chapter 01/04 - The Forgotten Age/TFA-The-Boundary-Beyond.svg",
    'the_city_of_archives':                           "Chapter 01/04 - The Forgotten Age/TFA-The-City-of-Archives.svg",
    'the_crash':                                      "Chapter 01/08 - Edge of the Earth/EOEC-The-Crash.svg",
    'the_depths_of_yoth':                             "Chapter 01/04 - The Forgotten Age/TFA-The-Depths-of-Yoth.svg",
    'the_devourers_cult':                             "Chapter 01/01r - Return to The Night of the Zealot/RTNOTZ-The-Devourer\u2019s-Cult.svg",
    'the_doom_of_arkham_part_1':                      "Chapter 01/11 - The Drowned City/TDCC-The-Doom-of-Arkham-Part-I.svg",
    'the_doom_of_arkham_part_2':                      "Chapter 01/11 - The Drowned City/TDCC-The-Doom-of-Arkham-Part-II.svg",
    'the_drowned_quarter':                            "Chapter 01/11 - The Drowned City/TDCC-The-Drowned-Quarter.svg",
    'the_eternal_slumber':                            "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-The-Eternal-Slumber.svg",
    'the_final_day':                                  "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Final-Day.svg",
    'the_first_day':                                  "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-First-Day.svg",
    'the_forest':                                     "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Forest.svg",
    'the_grand_vault':                                "Chapter 01/11 - The Drowned City/TDCC-The-Grand-Vault.svg",
    'the_great_seal':                                 "Chapter 01/08 - Edge of the Earth/EOEC-The-Great-Seal.svg",
    'the_heart_of_madness':                           "Chapter 01/08 - Edge of the Earth/EOEC-The-Heart-of-Madness.svg",
    'the_house_always_wins':                          "Chapter 01/02 - The Dunwich Legacy/DWL-The-House-Always-Wins.svg",
    'the_inescapable':                                "Chapter 01/11 - The Drowned City/TDCC-The-Inescapable.svg",
    'the_lair_of_dagon':                              "Chapter 01/07 - The Innsmouth Conspiracy/TIC-The-Lair-of-Dagon.svg",
    'the_last_king':                                  "Chapter 01/03 - The Path to Carcosa/PTC-The-Last-King.svg",
    'the_locals':                                     "Chapter 01/07 - The Innsmouth Conspiracy/TIC-The-Locals.svg",
    'the_longest_night':                              "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Longest-Night.svg",
    'the_lost_sister':                                "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Lost-Sister.svg",
    'the_miskatonic_museum':                          "Chapter 01/02 - The Dunwich Legacy/DWL-The-Miskatonic-Museum.svg",
    'the_nights_usurper':                             "Chapter 01/Scenarios/04 - Guardians of the Abyss/GOTA-The-Night\u2019s-Usurper.svg",
    'the_pallid_mask':                                "Chapter 01/03 - The Path to Carcosa/PTC-The-Pallid-Mask.svg",
    'the_pit_of_despair':                             "Chapter 01/07 - The Innsmouth Conspiracy/TIC-The-Pit-of-Despair.svg",
    'the_search_for_kadath':                          "Chapter 01/06 - The Dream-Eaters/TDE-The-Search-for-Kadath.svg",
    'the_second_day':                                 "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Second-Day.svg",
    'the_secret_name':                                "Chapter 01/05 - The Circle Undone/TCU-The-Secret-Name.svg",
    'the_silent_heath':                               "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Silent-Heath.svg",
    'the_thing_in_the_depths':                        "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Thing-in-the-Depths.svg",
    'the_twisted_hollow':                             "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Twisted-Hollow.svg",
    'the_unspeakable_oath':                           "Chapter 01/03 - The Path to Carcosa/PTC-The-Unspeakable-Oath.svg",
    'the_vale':                                       "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-The-Vale.svg",
    'the_vanishing_of_elina_harper':                  "Chapter 01/07 - The Innsmouth Conspiracy/TIC-The-Vanishing-of-Elina-Harper.svg",
    'the_wages_of_sin':                               "Chapter 01/05 - The Circle Undone/TCU-The-Wages-of-Sin.svg",
    'the_watcher':                                    "Chapter 01/05 - The Circle Undone/TCU-The-Watcher.svg",
    'the_western_wall':                               "Chapter 01/11 - The Drowned City/TDCC-The-Western-Wall.svg",
    'the_witching_hour':                              "Chapter 01/05 - The Circle Undone/TCU-The-Witching-Hour.svg",
    'threads_of_fate':                                "Chapter 01/04 - The Forgotten Age/TFA-Threads-of-Fate.svg",
    'to_the_forbidden_peaks':                         "Chapter 01/08 - Edge of the Earth/EOEC-To-the-Forbidden-Peaks.svg",
    'torch':                                          "Chapter 01/01 - Night of the Zealot/NOTZ-The-Gathering.svg",
    'torment':                                        "Chapter 02/201 - Brethren of Ash/BOA-Torment.svg",
    'transfiguration':                                "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Transfiguration.svg",
    'trapped_spirits':                                "Chapter 01/05 - The Circle Undone/TCU-Trapped-Spirits.svg",
    'traps':                                          "Chapter 01/04 - The Forgotten Age/TFA-Deadly-Traps.svg",
    'undersea_creatures':                             "Chapter 01/11 - The Drowned City/TDCC-Undersea-Creatures.svg",
    'undimensioned_and_unseen':                       "Chapter 01/02 - The Dunwich Legacy/DWL-Undimensioned-and-Unseen.svg",
    'union_and_disillusion':                          "Chapter 01/05 - The Circle Undone/TCU-Union-and-Disillusion.svg",
    'unspeakable_fate':                               "Chapter 01/05r - Return to The Circle Undone/RTTCU-Unspeakable-Fate.svg",
    'unstable_realm':                                 "Chapter 01/05r - Return to The Circle Undone/RTTCU-Unstable-Realm.svg",
    'venice':                                         "Chapter 01/Scenarios/02 - Carnevale of Horrors/COH-Carnevale-of-Horrors.svg",
    'venom':                                          "Chapter 01/04 - The Forgotten Age/TFA-Yig\u2019s-Venom.svg",
    'venomous_hate':                                  "Chapter 01/04r - Return to The Forgotten Age/RTTFA-Venomous-Hate.svg",
    'vile_experiments':                               "Chapter 01/Scenarios/05 - Murder at the Excelsior Hotel/MATEH-Vile-Experiments.svg",
    'vortex':                                         "Chapter 01/03 - The Path to Carcosa/PTC-The-Vortex-Above.svg",
    'waking_nightmare':                               "Chapter 01/06 - The Dream-Eaters/TDE-Waking-Nightmare.svg",
    'war_of_the_outer_gods':                          "Chapter 01/Scenarios/07 - War of the Outer Worlds/WOTOG-War-of-the-Outer-Gods.svg",
    'weaver_of_the_cosmos':                           "Chapter 01/06 - The Dream-Eaters/TDE-Weaver-of-the-Cosmos.svg",
    'where_doom_awaits':                              "Chapter 01/02 - The Dunwich Legacy/DWL-Where-Doom-Awaits.svg",
    'where_the_gods_dwell':                           "Chapter 01/06 - The Dream-Eaters/TDE-Where-the-Gods-Dwell.svg",
    'whippoorwills':                                  "Chapter 01/02 - The Dunwich Legacy/DWL-Whippoorwills.svg",
    'whippoorwills_ch2':                              "Chapter 02/201 - Brethren of Ash/BOA-Whippoorwills.svg",
    'whispers_of_hypnos':                             "Chapter 01/06 - The Dream-Eaters/TDE-Whispers-of-Hypnos.svg",
    'wilds':                                          "Chapter 01/04 - The Forgotten Age/TFA-The-Untamed-Wilds.svg",
    'witchcraft':                                     "Chapter 01/05 - The Circle Undone/TCU-Witchcraft.svg",
    'without_a_trace':                                "Chapter 01/09 - The Skarlet Keys/TSKC-Without-a-Trace.svg",
    'written_in_rock':                                "Chapter 01/10 - The Feast of Hemlock Vale/FHVC-Written-in-Rock.svg",
    'yog_sothoths_emissaries':                        "Chapter 01/02r - Return to Dunwich Legacy/RTDWL-Yog-Sothoth\u2019s-Emissaries.svg",
    'zoogs':                                          "Chapter 01/06 - The Dream-Eaters/TDE-Zoogs.svg"
  };

  /* Absolute, because these end up in a CSS custom property, and a relative url()
     in one resolves against the stylesheet rather than the page. */
  function url(file) {
    if (!file) return null;
    return new URL(DIR + file.split('/').map(encodeURIComponent).join('/'), document.baseURI).href;
  }

  /* The symbol printed on this card: its encounter set's, or its pack's. */
  function forCard(card) {
    if (!card) return null;
    return url(SETS[card.encounter_code] || PACKS[card.pack_code]);
  }

  global.GameIcons = {
    pack: function (code) { return url(PACKS[code]); },
    set: function (code) { return url(SETS[code]); },
    forCard: forCard
  };
})(window);
