/* Pack art, the texture behind each pack tile.

   GENERATED by docs/regen-packart.py from img/packs-art/ -- do not edit.
   Keyed by ArkhamDB pack code; each value is a tile cut to the pack
   card's square. Packs with no entry keep the star field. */
(function (global) {
  'use strict';

  var DIR = 'img/packs-art/';

  var TILES = {
    'core_2026': 'tiles/core_2026.jpg',
    'dwlc': 'tiles/dwlc.jpg',
    'dwlp': 'tiles/dwlp.jpg',
    'eoec': 'tiles/eoec.jpg',
    'eoep': 'tiles/eoep.jpg',
    'fhvc': 'tiles/fhvc.jpg',
    'ptcc': 'tiles/ptcc.jpg',
    'rcore': 'tiles/rcore.jpg',
    'tcuc': 'tiles/tcuc.jpg',
    'tdcc': 'tiles/tdcc.jpg',
    'tdec': 'tiles/tdec.jpg',
    'tfac': 'tiles/tfac.jpg',
    'ticc': 'tiles/ticc.jpg',
    'tskc': 'tiles/tskc.jpg',
  };

  /* Absolute, like GameIcons: the URL travels through a CSS custom
     property, and a relative one would resolve against the stylesheet
     that uses it (css/) instead of the page. */
  global.PackArt = {
    url: function (code) {
      var file = TILES[code];
      return file ? new URL(DIR + file, document.baseURI).href : null;
    }
  };
})(window);
