/* Pack art, the texture behind each pack tile.

   GENERATED by docs/regen-packart.py from img/packs-art/ -- do not edit.
   Keyed by ArkhamDB pack code; each value is a tile cut to the pack
   card's square. Packs with no entry keep the star field. */
(function (global) {
  'use strict';

  var DIR = 'img/packs-art/';

  var TILES = {
    'apot': 'tiles/apot.jpg',
    'blbe': 'tiles/blbe.jpg',
    'bob': 'tiles/bob.jpg',
    'bota': 'tiles/bota.jpg',
    'bsr': 'tiles/bsr.jpg',
    'coh': 'tiles/coh.jpg',
    'core': 'tiles/core.jpg',
    'core_2026': 'tiles/core_2026.jpg',
    'cotr': 'tiles/cotr.jpg',
    'dca': 'tiles/dca.jpg',
    'def': 'tiles/def.jpg',
    'dre': 'tiles/dre.jpg',
    'dwl': 'tiles/dwl.jpg',
    'dwlc': 'tiles/dwlc.jpg',
    'dwlp': 'tiles/dwlp.jpg',
    'enc': 'tiles/enc.jpg',
    'eoec': 'tiles/eoec.jpg',
    'eoep': 'tiles/eoep.jpg',
    'eotp': 'tiles/eotp.jpg',
    'fhvc': 'tiles/fhvc.jpg',
    'fhvp': 'tiles/fhvp.jpg',
    'har': 'tiles/har.jpg',
    'hoth': 'tiles/hoth.jpg',
    'iotv': 'tiles/iotv.jpg',
    'itd': 'tiles/itd.jpg',
    'jac': 'tiles/jac.jpg',
    'litas': 'tiles/litas.jpg',
    'lol': 'tiles/lol.jpg',
    'mtt': 'tiles/mtt.jpg',
    'nat': 'tiles/nat.jpg',
    'pnr': 'tiles/pnr.jpg',
    'promo': 'tiles/promo.jpg',
    'ptc': 'tiles/ptc.jpg',
    'ptcc': 'tiles/ptcc.jpg',
    'ptcp': 'tiles/ptcp.jpg',
    'rcore': 'tiles/rcore.jpg',
    'sfk': 'tiles/sfk.jpg',
    'sha': 'tiles/sha.jpg',
    'ste': 'tiles/ste.jpg',
    'tcu': 'tiles/tcu.jpg',
    'tcuc': 'tiles/tcuc.jpg',
    'tcup': 'tiles/tcup.jpg',
    'tdcc': 'tiles/tdcc.jpg',
    'tdcp': 'tiles/tdcp.jpg',
    'tde': 'tiles/tde.jpg',
    'tdec': 'tiles/tdec.jpg',
    'tdep': 'tiles/tdep.jpg',
    'tdg': 'tiles/tdg.jpg',
    'tdor': 'tiles/tdor.jpg',
    'tdoy': 'tiles/tdoy.jpg',
    'tece': 'tiles/tece.jpg',
    'tfa': 'tiles/tfa.jpg',
    'tfac': 'tiles/tfac.jpg',
    'tfap': 'tiles/tfap.jpg',
    'tftbw': 'tiles/tftbw.jpg',
    'tic': 'tiles/tic.jpg',
    'ticc': 'tiles/ticc.jpg',
    'ticp': 'tiles/ticp.jpg',
    'tmm': 'tiles/tmm.jpg',
    'tskc': 'tiles/tskc.jpg',
    'tskp': 'tiles/tskp.jpg',
    'tuo': 'tiles/tuo.jpg',
    'uau': 'tiles/uau.jpg',
    'wda': 'tiles/wda.jpg',
    'wgd': 'tiles/wgd.jpg',
    'win': 'tiles/win.jpg',
    'wos': 'tiles/wos.jpg',
  };

  /* Absolute, like GameIcons: the URL travels through a CSS custom
     property, and a relative one would resolve against the stylesheet
     that uses it (css/) instead of the page. */
  global.PackArt = {
    url: function (code) {
      var file = TILES[code];
      return file ? new URL(DIR + file, document.baseURI).href : null;
    }
  };
})(window);
