#!/usr/bin/env python3
"""Rebuild js/iconindex.js from what is actually in data/icons/.

    python docs/regen-iconindex.py

The Resources page lists every expansion symbol we vendor, and a static site has
no directory listing, so the file tree is baked into a manifest. The map CSV
beside the icons is not that manifest: it only carries the icons matched to an
ArkhamDB pack or encounter set, and it drifts from the folder as icons are
added. This walks the folder instead.

Groups come out in folder order — chapter, then the numbered set folders inside
it — which is the order the page shows them in. Only the standard library.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "data", "icons")
OUT = os.path.join(ROOT, "js", "iconindex.js")

HEAD = """/* Every expansion symbol under data/icons/, for the Resources page.

   Generated by docs/regen-iconindex.py — edit that, not this. A static site
   cannot list a directory, so the tree ships as data: the page needs the names
   to draw the grid, and the download needs them to fetch each file for the zip.

   `groups` is in folder order, which is release order; `files` holds bare file
   names, joined to `dir` + the group's `path` to reach the SVG. */
(function (global) {
  'use strict';

  var GROUPS = [
"""

TAIL = """  ];

  var n = 0;
  GROUPS.forEach(function (g) { n += g.files.length; });

  global.IconIndex = {
    dir: 'data/icons/',
    groups: GROUPS,
    count: n,
    /* Repo path of one icon, unencoded: the names carry spaces and curly
       apostrophes, so whatever needs a URL encodes the segments itself. */
    path: function (group, file) { return 'data/icons/' + group.path + '/' + file; }
  };
})(window);
"""


def js(s):
    """A JS string literal, ASCII-only: several names carry a curly apostrophe,
    and the generated file is plain ASCII like js/gameicons.js."""
    out = json.dumps(s, ensure_ascii=True)
    # json.dumps escapes for JSON, which is a subset of JS string syntax.
    return out


def walk():
    groups = []
    for dirpath, dirnames, filenames in os.walk(ICONS):
        dirnames.sort()
        svgs = sorted(f for f in filenames if f.lower().endswith(".svg"))
        if not svgs:
            continue
        rel = os.path.relpath(dirpath, ICONS).replace(os.sep, "/")
        groups.append((rel, svgs))
    return groups


def main():
    if not os.path.isdir(ICONS):
        sys.exit("no data/icons/ at %s" % ICONS)

    groups = walk()
    if not groups:
        sys.exit("data/icons/ holds no SVGs")

    body = []
    for rel, svgs in groups:
        # "Chapter 01/00 - Core" -> chapter "Chapter 01", label "00 - Core".
        parts = rel.split("/")
        chapter = parts[0]
        label = "/".join(parts[1:]) or parts[0]
        body.append(
            "    { path: %s,\n"
            "      chapter: %s,\n"
            "      label: %s,\n"
            "      files: [\n%s\n      ] }"
            % (
                js(rel),
                js(chapter),
                js(label),
                ",\n".join("        " + js(f) for f in svgs),
            )
        )

    # Platform newlines, like docs/regen-icons.py: js/ is CRLF on this checkout.
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEAD + ",\n".join(body) + "\n" + TAIL)

    total = sum(len(s) for _, s in groups)
    print("js/iconindex.js — %d icons in %d folders" % (total, len(groups)))


if __name__ == "__main__":
    main()
