"""Regenerate the pack-tile textures and js/packart.js from img/packs-art/.

Drop the source art in img/packs-art/ named <ffg-id>-<arkhamdb-code>.<ext>,
e.g. ahc60-rcore.png, then run from the project root:

    python docs/regen-packart.py

For every source image this writes img/packs-art/tiles/<code>.jpg: the art
scaled to cover the pack tile and centre-cropped to its square. The tiles
are what the page loads. CSS backgrounds are never lazy, so the catalogue
would otherwise pull every full-size source (1-1.5 MB each) the moment it
opened. It then rewrites js/packart.js, the code -> tile map app.js reads,
so a pack only asks for art that exists and the rest keep the star field
without a 404 each.

The sources are left untouched; the tiles and the map are generated, so
edit neither by hand.
"""
import os
import re
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'img', 'packs-art')
OUT = os.path.join(SRC, 'tiles')
JS = os.path.join(ROOT, 'js', 'packart.js')

# The pack tile is a 220px square; 1.5x covers a sharp hover on dense screens
# without paying for a full 2x of an image that is shown darkened. JPEG: the
# art is painted, it compresses well, and every tool opens it.
TILE_W, TILE_H = 330, 330
QUALITY = 82

NAME = re.compile(r'^(?P<ffg>[a-z0-9]+)-(?P<code>[a-z0-9_]+)$', re.I)
EXTS = {'.png', '.jpg', '.jpeg', '.webp'}


def cover_crop(img):
    """Scale to cover TILE_W x TILE_H, then crop the centre to exactly that."""
    img = img.convert('RGB')
    scale = max(TILE_W / img.width, TILE_H / img.height)
    w, h = round(img.width * scale), round(img.height * scale)
    img = img.resize((w, h), Image.LANCZOS)
    left, top = (w - TILE_W) // 2, (h - TILE_H) // 2
    return img.crop((left, top, left + TILE_W, top + TILE_H))


def main():
    os.makedirs(OUT, exist_ok=True)
    tiles, skipped = {}, []
    for name in sorted(os.listdir(SRC)):
        path = os.path.join(SRC, name)
        base, ext = os.path.splitext(name)
        if not os.path.isfile(path) or ext.lower() not in EXTS:
            continue
        m = NAME.match(base)
        if not m:
            skipped.append(name)
            continue
        code = m.group('code').lower()
        with Image.open(path) as img:
            cover_crop(img).save(os.path.join(OUT, code + '.jpg'), 'JPEG',
                                 quality=QUALITY, optimize=True, progressive=True)
        tiles[code] = 'tiles/' + code + '.jpg'

    # Anything in tiles/ that is not a current tile goes: a tile whose source
    # was removed, or one left from an earlier format.
    keep = set(f.split('/', 1)[1] for f in tiles.values())
    for name in os.listdir(OUT):
        if name not in keep:
            os.remove(os.path.join(OUT, name))

    rows = '\n'.join("    '%s': '%s'," % (c, f) for c, f in sorted(tiles.items()))
    with open(JS, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(
            "/* Pack art, the texture behind each pack tile.\n\n"
            "   GENERATED by docs/regen-packart.py from img/packs-art/ -- do not edit.\n"
            "   Keyed by ArkhamDB pack code; each value is a tile cut to the pack\n"
            "   card's square. Packs with no entry keep the star field. */\n"
            "(function (global) {\n"
            "  'use strict';\n\n"
            "  var DIR = 'img/packs-art/';\n\n"
            "  var TILES = {\n" + rows + "\n  };\n\n"
            "  /* Absolute, like GameIcons: the URL travels through a CSS custom\n"
            "     property, and a relative one would resolve against the stylesheet\n"
            "     that uses it (css/) instead of the page. */\n"
            "  global.PackArt = {\n"
            "    url: function (code) {\n"
            "      var file = TILES[code];\n"
            "      return file ? new URL(DIR + file, document.baseURI).href : null;\n"
            "    }\n"
            "  };\n"
            "})(window);\n")

    print('%d tile(s) -> img/packs-art/tiles/, js/packart.js rewritten' % len(tiles))
    for name in skipped:
        print('  skipped %s: expected <ffg-id>-<arkhamdb-code>' % name, file=sys.stderr)


if __name__ == '__main__':
    main()
